### PR TITLE
Uurstatistieken missen de laatste minuut of seconde

### PR DESCRIPTION
**Pull request by JeanMiK**
Just after midnight, when we compute the daily and hourly stats for the
day that has just passed, we don't have yet the full data for the first hour
of the new day; therefore, we may only compute the hourly stats for
target day + 0 hour, target day + 1 hour, ..., target day + 23 hour, but
*not* for target day + 24 hour.

Otherwise, as we have only 1 or two telegrams, we would already create an entry
for target day + 24 hours (= target day + 1 day + 0 hour) with an incorrect
consumption of 0 (or nearly 0).

On the following day, we would again look at the hour starting at the next
target day, but as the entry already existed, we would not recompute it.

This is the easiest fix for the problem. Alternatively, one could also
- wait for 1 am before computing stats
- change the code to update an already existing hourly cosumption

### Check

- [x] Make sure you are making a pull request against the `development` branch. Also you should start your branch off the `development` branch.

### CODE REVIEW

**Comment by JeanMiK** [comment]
Ah, I forgot to add a way to correct the already generated hourly stats without recomputing them completely from Scratch: in psqlplus or equivalent, one can simply execute teh following Statement:

update dsmr_stats_hourstatistics h
set 
electricity1=(select max(delivered_1)-min(delivered_1)
 from dsmr_consumption_electricityconsumption c where c.read_at between h.hour_start and
 (h.hour_start + interval '1 hour')),
electricity2=(select max(delivered_2)-min(delivered_2)
 from dsmr_consumption_electricityconsumption c where c.read_at between h.hour_start and
 (h.hour_start + interval '1 hour'))
 where date_trunc('day', h.hour_start)=h.hour_start
 ;

**Comment by JeanMiK** [comment]
Further correction for every hourly consumption

As the total hourly consumption is computed by the difference of
the meter readings between the end of the hour and the beginning
(and not by *summing* individual consumptions by minute), we
must consider the reading at [start + 1 hour] itself, therefore
we need to use 'lte' for the upper bound in the filter of
"consumption_by_range"

The current code is systematically ignoring the consumption of
the last minute of the hour.

**Comment by dennissiemensma** [comment]
Thanks for reporting your issue. I'll have a look at it, as I'll need some examples and data for tests first.

**Comment by JeanMiK** [comment]
At least on my system, the first bug was very obvious: almost every hourly consumption starting at midnight had a ‘consumption’ of either 0 or a very small number, depending on whether at the time of the daily stats generation, there was only 1 or slightly more per minute readings.

 

I noticed the second problem (the hourly consumptions missing the consumption of the very last minute) when I recomputed myself yesterday’s hourly consumptions in order to fill a gap caused by the downtime of my dsmr instance, the mistake is fairly obvious once you think about it.

 

I must admit however that after a bit of thinking, it shows that my initial fix is incomplete as well: 

 

The original code was *always* trying to compute 25 hourly consumptions (start+0, start+1, …, start+24), thereby creating on most days 1 hourly consumption belonging already to the next day and therefore (incorrectly) empty (or almost empty), an entry that would not be corrected the next day. 

 

With my fix, we compute every day 24 hourly consumptions, which is correct on *almost* all days, except

*	When we switch to DST, where 24 consumptions is still 1 too much -> same problem as today
*	When we switch from DST to STD, where 24 consumptions is 1 too few, we really should have computed 25

 

I will soon update my pull request with a revised fix.

 

Regards,

 

Jean-Marie

**Comment by JeanMiK** [comment]
Illustration of code:

```
>>> start_of_day=timezone.make_aware(timezone.datetime(2019,10,27))
>>> start_of_day
datetime.datetime(2019, 10, 27, 0, 0, tzinfo=<DstTzInfo 'Europe/Paris' CEST+2:00:00 DST>)
>>> test_day = start_of_day + timezone.timedelta(days=1)
>>> test_day
datetime.datetime(2019, 10, 28, 0, 0, tzinfo=<DstTzInfo 'Europe/Paris' CEST+2:00:00 DST>)
>>> target_day=date(2019, 10, 27)
>>> next_day=target_day + timezone.timedelta(days=1)
>>> next_day
datetime.date(2019, 10, 28)
>>> end_of_day = timezone.make_aware(timezone.datetime(year=next_day.year,month=next_day.month, day=next_day.day))
>>> end_of_day
datetime.datetime(2019, 10, 28, 0, 0, tzinfo=<DstTzInfo 'Europe/Paris' CET+1:00:00 STD>)
>>> hour_start = start_of_day
>>> while (hour_start < end_of_day):
...   print("Start of hour ", hour_start, " is still before midnight, ", end_of_day)
...   hour_start = hour_start + timezone.timedelta(hours=1)
...
Start of hour  2019-10-27 00:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 01:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 02:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 03:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 04:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 05:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 06:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 07:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 08:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 09:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 10:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 11:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 12:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 13:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 14:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 15:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 16:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 17:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 18:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 19:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 20:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 21:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 22:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-27 23:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
Start of hour  2019-10-28 00:00:00+02:00  is still before midnight,  2019-10-28 00:00:00+01:00
>>>
```

As one can see, yesterday, it took 25 hours to reach the next midnight, and the new code will go there.

**Comment by dennissiemensma** [comment]
Thanks, I'll write some scenario's accordingly to make sure it's checked by tests.

**Comment by dennissiemensma** [comment]
I've added tests for one of the issues, so it won't happen again. Next is the hours per day issue.

**Comment by dennissiemensma** [comment]
I've now also fixed the other issue, regarding DST transitions. It will be included in the next release.

Thanks a lot for reporting this, as I didn't knew DST transitions do not work well with timedelta's.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v2.10](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v2.10.0)

**Pull request closed without merging**
